
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: nightscout-migration-decorator
spec:
  resources:
    - apiVersion: nightscout.k8s/v1alpha1
      resource: nightscoutinstances
      annotationSelector:
        nightscout.k8s/migrate-from: "*"
  attachments:
    - apiVersion: batch/v1
      resource: jobs
  hooks:
    sync:
      webhook:
        url: http://deployment-controller:3000/metacontroller/decorator/sync
