
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: storage-decorator
spec:
  resources:
    - apiVersion: v1
      resource: secrets
      labelSelector:
        matchExpressions:
          - key: "storage.nightscout.org/account"
            operator: "Exists"
  attachments:
    - apiVersion: v1
      resource: persistentvolumeclaims
  hooks:
    sync:
      webhook:
    customize:
      webhook:
        url: http://deployment-controller:3000/metacontroller/decorator/storage/customize
        url: http://deployment-controller:3000/metacontroller/decorator/storage/sync
